### ISSUE TITLE
Interpreting the results

### ISSUE THREAD

**Issue by pudkeaayush** [jmiller656/DiscoGAN-Tensorflow#4]
Hey,
Just wanted to confirm how to interpret the results. Does the image generated in generator a -> b , say img0.jpg mean that it is translating the image 000001.jpg from the celebA dataset from a female to male?

Well, in case of two custom datasets, say A and B, what does the generated image say img140.jpg signify?

Regards,
Raju

**Comment by jmiller656** [comment]
Thinking about this, I've realized that the output is a bit counter-intuitive. While training the network has a sampling rate and a sample overlap distance.
For the sake of example, let's say you have a sample frequency of 10 and a sample overlap of 500
In this case, every 10 iterations of training, a random image will be chosen from both datasets, a and b. The outputs for these images will be computed and saved in their respective directories with a name following this scheme:
`imgx.png`
where x is the current training iteration % your sample overlap (500 by default). 
I do this so that the hard drive on the computer running this is not overfilled with images.


As for the image directories, there are four of them. `generator a->b`, `generator b->a`, `reconstruct a`, and `reconstruct b`. Generator a->b is the result of DiscoGAN attempting to map an image from dataset A to domain B (and vice versa for the other generator folder). Reconstruct A is the result of DiscoGAN attempting to reconstruct the original image that was passed into it. After a bit of training, you can usually use the reconstructed image as a fairly decent reference for what was passed into the generator initially. Ex: 

Let's say I have img100.png in reconstruct a. After a long enough period of training (usually reconstruction progresses faster, in my experience) you should see that the img100.png looks very similar to an image from your domain A dataset. Then, if you look at img100.png in your generator a->b folder, you'll see DiscoGAN's attempt at mapping that image to domain b. 

Hope this helps! I plan on making this a bit better in the future by adding image summaries to tensorboard so you can just watch those while training and also adding functions to simplify sampling from the neural network after training. This can be done now by creating a discoGAN and calling resume(), but you would have to write some tensorflow code on your own to actually compute the outputs of the network at the moment.

**Comment by pudkeaayush** [comment]
Thank you for the detailed feedback. :)
